#!/usr/bin/env sh

# Generate a static website using Zola
# by David Oniani <onianidavid@gmail.com>
# License: GNU GPLv3

cd _website || return

zola build

cp -f CNAME public/
cp -Rf public/* ../
rm -r public

cd .. || return
