#!/usr/bin/env sh

# Generate a static website using Zola
# by David Oniani <onianidavid@gmail.com>
# License: GNU GPLv3

cd _website || return

zola build

cp static/CNAME public/
cp static/favicon.ico public/

mv public/* ../

rm -rf public

cd .. || return

printf "Done!\n"
